name: Goreleaser

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
